[package]
name = "typst2docx"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
thiserror = "2.0.20"

[lints.rust]
missing_docs = "warn"
unexpected_cfgs = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "warn"

[dev-dependencies]
assert_cmd = "2.2.2"
predicates = "3.1.4"
